project_id = "kpbqmkgpvwmctjnwoqmh"

[functions.create-tpay-transaction]
verify_jwt = false

[functions.confirm-blik-payment]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.process-blik-payment]
verify_jwt = false

[functions.agent-webhook]
verify_jwt = false

[functions.send-to-make]
verify_jwt = false

[functions.send-client-data-email]
verify_jwt = false